### ISSUE TITLE
New install, app not working

### ISSUE THREAD

**Issue by gmacor** [mglaman/conductor#6]
I have installed Conductor on a Win 10 machine with XAMPP.
Status:
The buttons " Add new project" and "Settings" are not active ( i can click, but no event).

Please check the following:

- i have installed xampp on C:\xampp\
- during the Composer setup i need to specify where is located php.exe ( C:\xampp\php )

- i have installed Conductor on C:\www_tools\conductor
- i saw the install of Composer that is bundled with Conductor, but with no interaction to ask about the php.exe location

I think this is the cause of the issue.

On another hand, is needed to install Conductor on some specific directory (e.g. inside XAMPP ) ?

After your response, i will do a fresh install.

Thank you.

Gabriel

**Comment by mglaman** [comment]
You can install Conductor anywhere. And it doesn't bundle Composer yet (see #1.) So it expects PHP to be available and Composer.

I haven't used a Windows machine in 10+ years, solely Linux or macOS. I have a friend with a Windows 10 machine and will see if they can aid in troubleshooting.

**Comment by gmacor** [comment]
I deleted the Conductor directory and make a new install.

1. During the install i get this:

> getcomposer@1.3.2 postinstall C:\www_tools\conductor\node_modules\getcomposer
> node index.js


Downloading composer

...............................................................
All settings correct for using Composer

Downloading 1.2.1...


Composer successfully installed to: C:\www_tools\conductor\node_modules\getcomposer\composer.phar
Use it: php composer.phar

Composer successfully installed
............................................................................................................

2. Post install: Create and Settings not active.
Conductor try to use the composer that is installed above? This composer install is not aware of location of php.exe from my XAMPP.

3. How to uninstall completely conductor app for a new fresh install? 
Just delete these folders?
C:\www_tools\conductor
C:\User\MyName\AppData\Roaming\Conductor

**Comment by mglaman** [comment]
Create and Settings currently do not work, they're in the UI but didn't land quite yet.

Yes, just remove the folder and the AppData

**Comment by gmacor** [comment]
Open an existing composer project should work?

**Comment by gmacor** [comment]
Unfortunately, the install of a Drupal project with composer from command prompt end with  an exception error.

![image](https://cloud.githubusercontent.com/assets/23008533/19656692/ab9ed520-9a29-11e6-9c19-d977a37a260d.png)

I will need to solve this in order to open the project in Conductor.

**Comment by gmacor** [comment]
Managed to install Drupal Social with composer.
Conductor can't open the project.
Here is the file: npm-debug.log


[npm-debug.txt](https://github.com/mglaman/conductor/files/548740/npm-debug.txt)

**Comment by mglaman** [comment]
@gmacor okay, thanks for debug. I honestly have no clue how well Node + Windows plays. 

```
14 verbose stack Error: conductor@0.1.0 start: `electron .`
14 verbose stack Exit status 2147483651
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\$USER\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\$USER\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid conductor@0.1.0
16 verbose cwd C:\www_tools\conductor
```

This looks like an error with starting the process of just launching the app via Electron. I'll try to do some digging.

**Comment by mglaman** [comment]
Can you try running with `npm start --verbose`?

It looks similar to https://github.com/electron/electron/issues/7152.

**Comment by gmacor** [comment]
This is the log file after npm start --verbose 
[npm-debug _R2.log.txt](https://github.com/mglaman/conductor/files/548814/npm-debug._R2.log.txt)

**Comment by gmacor** [comment]
[372:1024/224714:FATAL:render_process_host_impl.cc(566)] Check failed: !BrowserM              ainRunner::ExitedMainMessageLoop().
Backtrace:
        (No symbol) [0x004EB1B7]
        (No symbol) [0x004E5F71]
        icu_56::BreakIterator::isBufferClone [0x00716A8A+1334186]
        icu_56::BreakIterator::isBufferClone [0x006733E5+664837]
        icu_56::BreakIterator::isBufferClone [0x00682180+725664]
        icu_56::BreakIterator::isBufferClone [0x0067D639+706393]
        icu_56::BreakIterator::isBufferClone [0x0067C92C+703052]
        (No symbol) [0x003C9EBC]
        (No symbol) [0x003CCA39]
        (No symbol) [0x0042468D]
        (No symbol) [0x00428B85]
        (No symbol) [0x0040956B]
        (No symbol) [0x0040570C]
        (No symbol) [0x0040576E]
        (No symbol) [0x00409556]
        (No symbol) [0x004088AF]
        (No symbol) [0x004080C1]
        v8::Locker::IsLocked [0x0FFE7020+1188768]
        v8::Locker::IsLocked [0x0FEF7B5E+208606]
        v8::Locker::IsLocked [0x0FEE827F+144895]

**Comment by gmacor** [comment]
[372:1024/224714:FATAL:render_process_host_impl.cc(566)] Check failed: !BrowserM              ainRunner::ExitedMainMessageLoop().
Backtrace:
        (No symbol) [0x004EB1B7]
        (No symbol) [0x004E5F71]
        icu_56::BreakIterator::isBufferClone [0x00716A8A+1334186]
        icu_56::BreakIterator::isBufferClone [0x006733E5+664837]
        icu_56::BreakIterator::isBufferClone [0x00682180+725664]
        icu_56::BreakIterator::isBufferClone [0x0067D639+706393]
        icu_56::BreakIterator::isBufferClone [0x0067C92C+703052]
        (No symbol) [0x003C9EBC]
        (No symbol) [0x003CCA39]
        (No symbol) [0x0042468D]
        (No symbol) [0x00428B85]
        (No symbol) [0x0040956B]
        (No symbol) [0x0040570C]
        (No symbol) [0x0040576E]
        (No symbol) [0x00409556]
        (No symbol) [0x004088AF]
        (No symbol) [0x004080C1]
        v8::Locker::IsLocked [0x0FFE7020+1188768]
        v8::Locker::IsLocked [0x0FEF7B5E+208606]
        v8::Locker::IsLocked [0x0FEE827F+144895]


npm verb lifecycle conductor@0.1.0~start: unsafe-perm in lifecycle true
npm verb lifecycle conductor@0.1.0~start: PATH: C:\Users\Gabriel\AppData\Roaming              \npm\node_modules\npm\bin\node-gyp-bin;C:\www_tools\conductor\node_modules\.bin;              C:\Users\Gabriel\bin;C:\Program Files\Git\mingw32\bin;C:\Program Files\Git\usr\l              ocal\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Fi              les\Git\mingw32\bin;C:\Program Files\Git\usr\bin;C:\Users\Gabriel\bin;C:\Program              Data\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbe              m;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Calibre2;C:\Progra              m Files\Skype\Phone;C:\xampp\php;C:\Program Files\Git\cmd;C:\Program Files\Commo              n Files\Adobe\AGL;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs;C:\Pr              ogram Files\Microsoft VS Code\bin;C:\Users\Gabriel\AppData\Local\Microsoft\Windo              wsApps;C:\Users\Gabriel\AppData\Roaming\Composer\vendor\bin;C:\Users\Gabriel\App              Data\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\u              sr\bin\core_perl
npm verb lifecycle conductor@0.1.0~start: CWD: C:\www_tools\conductor
npm info lifecycle conductor@0.1.0~start: Failed to exec start script
npm verb stack Error: conductor@0.1.0 start: `electron .`
npm verb stack Exit status 2147483651
npm verb stack     at EventEmitter.<anonymous> (C:\Users\Gabriel\AppData\Roaming              \npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Users\Gabriel\AppData\Roaming              \npm\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:829:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_proces              s.js:211:5)
npm verb pkgid conductor@0.1.0
npm verb cwd C:\www_tools\conductor
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gabriel\\AppData              \\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start" "--verbose"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! conductor@0.1.0 start: `electron .`
npm ERR! Exit status 2147483651
npm ERR!
npm ERR! Failed at the conductor@0.1.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the conductor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs conductor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls conductor
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\www_tools\conductor\npm-debug.log

**Comment by mglaman** [comment]
Okay, I have AppVeyor running which is a CI for Windows. Looks like we're going to need to get some tests written.
